name: business_card_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - lib/images/
  
  fonts:
      - family: Pacifico
        fonts:
          - asset: lib/fonts/Pacifico-Regular.ttf
      - family: Source Sans 3
        fonts:
          - asset: lib/fonts/SourceSans3-Regular.ttf